server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /luojun
    username: luojun
    password: 1234
  cloud:
    bus:   #消息总线配置
      enabled: true
      trace:
        enabled: true
management:   #暴露bus refresh
  endpoints:
    web:
      exposure:
        include: bus-refresh
my:
  name: wangwu