server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: feign-consumer
  zipkin:
    base-url: http://localhost:9411  #指定zipkin服务器地址
    sleuth:
      web:
        client:
          enabled: true  #开启sleuth(链路追踪功能)功能
      sampler:
        probability: 1.0   #当设置为1.0时就是链路数据100%收集到zipkin-server
ribbon:
  ReadTimeout: 6000   #ribbon读取时间超过6s
  ConnectTimeout: 6000 #ribbon读取时间超过6s
  MaxAutoRetries: 1     #当ribbon第一此尝试连接6s失败了之后，会再尝试连接一次该服务器6s失败就进行下一次
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false # 对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的，所以设置为false
hystrix:
  command:   #执行命令相关
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 18000   #这里是要>=(1+1+1)*6
              #如果配置ribbon的重试，hystrix的超时时间要大于ribbon的超时时间，ribbon才会重试
              #hystrix的超时时间=(1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout 比较好，具体看需求
feign:
  hystrix:
    enabled: true  #开启feign对hystrix熔断的支持才行