server:
  port: 9100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ribbon-consumer
  zipkin:
    base-url: 9411  #指定zipkin服务器地址
    sleuth:
      web:
        client:
          enabled: true  #开启sleuth(链路追踪功能)功能
      sampler:
        probability: 1.0   #当设置为1.0时就是链路数据100%收集到zipkin-server
hystrix:
  command:   #执行命令相关
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000  #超时设置，超过指定的时间，那么就执行fallback操作