server:
  port: 11000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-service
zuul:     #网关就是实现分发，把请求分发到对应的服务，也是负载均衡和nginx一个原理。
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: ribbon-consumer
    feidn:
      path: /feign/**
      serviceId: feign-consumer
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000  #超时设置，超过指定的时间，那么就执行fallback操作
ribbon:
  ReadTimeout: 6000   #ribbon读取时间超过6s
  ConnectTimeout: 6000 #ribbon读取时间超过6s,那么不管是hystrix熔断还是出现异常，都直接进入熔断方法